config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'about', to: 'about#index'
  get 'about/my-share', to: 'about#my_share', as: 'my_share'
  get 'about/other-share-with-me', to: 'about#other_share_with_me', as: 'other_share_with_me'
  resources :profiles
  resources :locations
  root to: 'about#index'
end

app/models/access.rb
class Access < ApplicationRecord
    validates :share_type, presence: true, length: { minimum: 1 }
    has_many :location
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
    validates :latitude, presence: true, length: { minimum: 1 }
    validates :longitude, presence: true, length: { minimum: 1 }
    #belongs_to :user
    belongs_to :access

    has_many :user_locations
    has_many :users, through: :user_locations
end

app/models/profile.rb
class Profile < ApplicationRecord
    validates :first_name, presence: true, length: { minimum: 1 }, format: { with:  /\A[a-zA-Z0-9 ]+\z/ }
    validates :last_name, presence: true, length: { minimum: 1 }, format: { with:  /\A[a-zA-Z0-9 ]+\z/ }
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  has_many :user_locations
  has_many :locations, through: :user_locations
end

app/models/user_location.rb
class UserLocation < ApplicationRecord
    belongs_to :user
    belongs_to :location
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    before_action :authenticate_user!
    def index
        @users = User.all
    end
    def my_share
        if current_user
            @mylocations = Location.where(user_id: current_user)
        end
    end

    def other_share_with_me
        if current_user
            @shared_locations = get_shared_locations
        end
    end

    private
    def get_shared_locations
        locations_array = []
        current_user.user_locations.each do |user_location|
            locations_array << user_location.location
        end
        return locations_array
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    before_action :authenticate_user!

    def index
        # @addresses = Address.all
    end

    def show
        @location = Location.find_by(:id=> params[:id])
    end

    def new
        @location = Location.new
        @users = User.all
    end
    
    def edit
         @location = Location.find_by(:id=> params[:id])
         @users = User.all
    end

    def create
        @location = Location.new(location_params)
        @location.user_id = current_user.id
        @location.access_id = Access.first.id
        if @location.save
            if params["user_ids"]
                if !params["user_ids"].empty?
                    params["user_ids"].each do |id|
                        UserLocation.create(user_id: id, location_id:@location.id)
                    end
                else
                end
            end
            redirect_to location_path(@location), success: "Address is successfully created."
        else
            render action: :new, error: "Error while creating new address"
        end
    end

    def update
        @location = Location.find_by(:id=> params[:id])
        if @location.update(location_params)
            if !params["user_ids"].empty?
                params["user_ids"].each do |id|
                    UserLocation.create(user_id: id, location_id:@location.id)
                end
            else
            end
            flash[:success] = "Location is successfully updated."
            redirect_to location_path(@location)
        else
            flash[:error] = "Error while updating location"
            render :edit
        end
    end

    def destroy
        # if @address.destroy
        #     flash[:success] = "Profile #{@profile.first_name} removed successfully"
        #     redirect_to profiles_path
        # else
        #     flash[:error] = "Error while removing story!"
        #     redirect_to profile_path(@profile)
        # end 
    end

    private
    def location_params
        params.require(:location).permit(:latitude, :longitude, user_ids:[])
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!

    def index
        @profile = current_user.profile
    end

    def show
        @profile = Profile.find_by(:id=> params[:id])
    end

    def new
        @profile = Profile.new
    end
    
    def edit
        @profile = Profile.find_by(:id=> params[:id])
    end

    def create
        @profile = Profile.new(profile_params)
        @profile.user_id = current_user.id
        if @profile.save
            redirect_to profile_path(@profile), success: "Profile is successfully created."
        else
            render action: :new, error: "Error while creating new profile"
        end
    end

    def update
        @profile = Profile.find_by(:id=> params[:id])
        if @profile.update(profile_params)
            flash[:success] = "Profile #{@profile.first_name} is successfully updated."
            redirect_to profile_path(@profile)
        else
            flash[:error] = "Error while updating story"
            redirect_to profile_path(@profile)
        end
    end

    def destroy
        if @profile.destroy
            flash[:success] = "Profile #{@profile.first_name} removed successfully"
            redirect_to profiles_path
        else
            flash[:error] = "Error while removing story!"
            redirect_to profile_path(@profile)
        end 
    end

    private
    def profile_params
        params.require(:profile).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
  
<H2> List of all User </H2>
<% @users.each do |user| %>
  <%= user.email %> </br>
<% end %>

app/views/about/my_share.html.erb
<H2> The place you have share </H2> 
<% if !@mylocations.empty? %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Coordinate1</th>
        <th scope="col">Coordinate2</th>
      </tr>
    </thead> 
    <tbody>
    <% @mylocations.each do |location| %>
      <tr>
        <th scope="row">1</th>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/about/other_share_with_me.html.erb
<H2> The place other people have shared with you </H2> 
<% if !@shared_locations.empty? %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Coordinate1</th>
        <th scope="col">Coordinate2</th>
      </tr>
    </thead> 
    <tbody>
    <% @shared_locations.each do |location| %>
      <tr>
        <th scope="row">1</th>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/addresses/_form.html.erb
<%= form_with(model: address, local: true, :html => {:id => "addressForm"})  do |form| %>
    
    <% if address.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>
        <ul>
          <% address.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %> 
    <div class="form-group">
      <label for="area"> Area : </label>
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%= form.text_field :area, :class => 'form-control', :id => 'area-field', :onkeyup => "validate_area();" %>
        </div>
      <span id="areaError"></span>
    </div>
    <div class="form-group">
      <label for="landmark">  Landmark : </label>
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%= form.text_field :landmark, :class => 'form-control', :id => 'landmark-field', :onkeyup => "validate_landmark();" %>
        </div>
      <span id="landmarkError"></span>
    </div>

    <div class="form-group">
      <label for="city">  City : </label>
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%= form.text_field :city, :class => 'form-control', :id => 'city-field', :onkeyup => "validate_landmark();" %>
        </div>
      <span id="cityError"></span>
    </div>

    <div class="form-group">
      <label for="state">  State : </label>
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%= form.text_field :state, :class => 'form-control', :id => 'state-field', :onkeyup => "validate_state();" %>
        </div>
      <span id="stateError"></span>
    </div>

    <div class="form-group">
      <label for="country">  Country : </label>
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%= form.text_field :country, :class => 'form-control', :id => 'country-field', :onkeyup => "validate_country();" %>
        </div>
      <span id="countryError"></span>
    </div>

    <div class="actions">
    <%= form.submit class: 'btn submit-btn',id: "submitAddress", :onclick => "check_blank();"  %>
    <%= link_to 'Back', root_path, :class => 'btn back-btn '%>
  </div>
<% end %>
</div>

app/views/addresses/edit.html.erb
<%= render 'form', address: @address %>

app/views/addresses/new.html.erb
Add New Location:
<div id="map">
  <!-- Your map will be shown inside this div-->
 </div>
</body>
<script src="https://openlayers.org/en/v4.6.5/build/ol.js" type="text/javascript"></script>
 <!-- Openlayesr JS fIle -->
 <!-- Our map file -->

 <div id="display">
 </div>

<script type="text/javascript">
window.onload = init;
function init(){
var map = new ol.Map({
        target: 'map',
        layers: [
          new ol.layer.Tile({
            source: new ol.source.OSM()
          })
        ],
        view: new ol.View({
          center: ol.proj.fromLonLat([0,0]),
          zoom: 1 //Initial Zoom Level
        })
        
      });
      map.on('click', function(e){
            console.log(e.coordinate);
            document.getElementById('display').innerHTML = "You have selected -> " + e.coordinate;
        })
    }
</script>
<%= render 'form', address: @address %>

app/views/addresses/show.html.erb
Area: <%= @address.area %></br>
Landmark: <%= @address.landmark %> </br>
City: <%= @address.city %></br>
State: <%= @address.state %></br>
Country: <%= @address.country %></br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://openlayers.org/en/v4.6.5/css/ol.css" type="text/css">
    <!-- Openlayers CSS file-->
    
    <style type="text/css">
      #map{
      width:100%;
      height:600px;
      }
    </style>
  </head>
  <style>
    nav.navbar.topnav ul > li a.nav-link {
      padding: 10px 20px;
      color: #000;
      margin: 10px 2px;
      font-size: 14px;
    }
    section{padding-bottom:50px;}
    a.navbar-brand.topnav {
      height: auto;
    }
    .top-bar.navbar-default {
      padding: 10px 0;
    }
    .top-bar.navbar-default ul.list-inline {
      margin: 0;
    }
    .top-bar.navbar-default {
      padding: 10px 0;
      background: #333436;
      color: #fff;
    }
    .top-bar.navbar-default a {
      color: #fff;
    }   
    .top-bar.navbar-default a:hover {
      background: none;
      text-decoration: none;
    }
    a:hover {
      background: none;
      text-decoration: none;
    }

    nav.navbar.topnav {
      margin: 0 !important;
    }
    nav.navbar.topnav + hr {
      margin: 10px 0 0;
    }
    nav.navbar.topnav ul > li a.nav-link {
      padding: 10px 20px;
      color: #000;
      margin: 10px 2px;
    }
    nav.navbar.topnav ul > li a.nav-link:hover {
      background: #2B2B71;
    }
    .navbar-toggle span.icon-bar {
      background: #2B2B71;
    } 
    .navbar-nav>li>a:hover {
      color: #fff;
      background: #2B2B71;
    }
    .nav-item:hover{
      background-color: #2d2b75;
    }
    @media screen and (max-width: 480px) {
      .list-inline1> li {
      float: center;
      margin-right: 40px;
    }
    .top-bar.navbar-default {
      padding: 0px 0px;
    }
</style>

  <body>
    <div class="top-bar navbar-default" oncontextmenu="return false;">
            <div class="container" oncontextmenu="return false;">
                <div class="row">
                    <div class="col-sm-6">
                        <ul class="list-inline">
                            <li><i class="fa fa-envelope-o" style="font-size:11px;"></i> <a href="mailto:indrajitnaiya09@gmail.com(opens in new tab)?Subject=low-inventory-notification-app" target="_top">indrajitnaiya09@gmail.com</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 text-right">
                        <ul class="list-inline list-inline1">
                            <li><a href="https://twitter.com/indrajitnaiya09" target="_blank"><i class="fa fa-twitter" style="font-size:17px;color:white"></i></a></li> &nbsp&nbsp
                            <li><a href="https://www.facebook.com/indrajitnaiya09" target="_blank"><i class="fa fa-facebook" style="font-size:17px;color:white"></i></a></li> &nbsp&nbsp
                            <li><a href="https://www.instagram.com/indrajitnaiya09/" target="_blank"><i class="fa fa-instagram" style="font-size:17px;color:white"></i></a></li> &nbsp&nbsp
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <nav class="navbar  topnav" role="navigation" oncontextmenu="return false;">
            <div class="container topnav">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <ul class="nav navbar-nav navbar-right">
                      <li class="nav-item"><%= link_to "Home", root_path %></li>
                      <li class="nav-item"> <%= link_to "Add Location", new_location_path %></li>
                      <% if user_signed_in? %>
                          <li class="nav-item"> <%= link_to "Myshare", my_share_path %></li>
                          <li class="nav-item"> <%= link_to "Shared with Me", other_share_with_me_path %></li>
                          <li class="nav-item"> <%= link_to "Account Setting", edit_user_registration_path %></li>
                          <li class="nav-item"> <%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                          <% if current_user.profile %>
                            <li class="nav-item"><%= link_to "Profile", profile_path(current_user.profile)%></li>
                          <% else %>
                            <li class="nav-item"><%= link_to "Create Profile", new_profile_path %></li>  
                          <% end %>
                      <% else %>
                      <% end %>
                    </ul>

                </div>
              </div>
        </nav><hr/>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true, :html => {:id => "locationForm"})  do |form| %>
    
    <% if location.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>
        <ul>
          <% location.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %> 
    <div class="form-group">
      <label for="latitude"> Latitude : </label>
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%= form.text_field :latitude, :class => 'form-control', :id => 'latitude-field', :onkeyup => "validate_latitude();" %>
        </div>
      <span id="areaError"></span>
    </div>
    <div class="form-group">
      <label for="longitude">  Longitude : </label>
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%= form.text_field :longitude, :class => 'form-control', :id => 'longitude-field', :onkeyup => "validate_longitude();" %>
        </div>
      <span id="longitudeError"></span>
    </div>

    <% @users.each do |user| %>
      <div class="field">
      <label class="form-label"><%= check_box_tag "user_ids[]", user.id, :id => "user_ids_#{user.id}" %><%= user.email %></label>
    </div>
    <% end %>

    

    <div class="actions">
    <%= form.submit class: 'btn submit-btn',id: "submitAddress", :onclick => "check_blank();"  %>
    <%= link_to 'Back', root_path, :class => 'btn back-btn '%>
  </div>
<% end %>
</div>

<script type="text/javascript">
window.onload = init;
function init(){
var map = new ol.Map({
        target: 'map',
        layers: [
          new ol.layer.Tile({
            source: new ol.source.OSM()
          })
        ],
        view: new ol.View({
          center: ol.proj.fromLonLat([0,0]),
          zoom: 1 //Initial Zoom Level
        })
        
      });
      map.on('click', function(e){
            console.log(e.coordinate);
            document.getElementById('latitude-field').value = e.coordinate[0];
            document.getElementById('longitude-field').value = e.coordinate[1];
        })
    }
</script>

app/views/locations/edit.html.erb
Edit Location:
<div id="map">
  <!-- Your map will be shown inside this div-->
 </div>
</body>
<script src="https://openlayers.org/en/v4.6.5/build/ol.js" type="text/javascript"></script>
 <!-- Openlayesr JS fIle -->
 <!-- Our map file -->

 <div id="display">
 </div>


<%= render 'form', location: @location %>

app/views/locations/new.html.erb
Add New Location:
<div id="map">
  <!-- Your map will be shown inside this div-->
 </div>
</body>
<script src="https://openlayers.org/en/v4.6.5/build/ol.js" type="text/javascript"></script>
 <!-- Openlayesr JS fIle -->
 <!-- Our map file -->

 <div id="display">
 </div>


<%= render 'form', location: @location %>

app/views/locations/show.html.erb
<%= @location.longitude %>
<%= @location.latitude %>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true, :html => {:id => "profileForm"})  do |form| %>
    
    <% if profile.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
        <ul>
          <% profile.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %> 
    <div class="form-group">
      <label for="first_name"> First Name : </label>
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%= form.text_field :first_name, :class => 'form-control', :id => 'first-name-field', :onkeyup => "validate_first_name();" %>
        </div>
      <span id="firstNameError"></span>
    </div>
    <div class="form-group">
      <label for="last_name"> Last Name : </label>
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%= form.text_field :last_name, :class => 'form-control', :id => 'last-name-field', :onkeyup => "validate_last_name();" %>
        </div>
      <span id="lastNameError"></span>
    </div>

    <div class="actions">
    <%= form.submit class: 'btn submit-btn',id: "submitProfile", :onclick => "check_blank();"  %>
    <%= link_to 'Back', root_path, :class => 'btn back-btn '%>
  </div>
<% end %>
</div>

app/views/profiles/edit.html.erb
<%= render 'form', profile: @profile %>

app/views/profiles/new.html.erb
<%= render 'form', profile: @profile %>

app/views/profiles/show.html.erb
<H2>My Profile <H2>
<H4>First Name : <%=@profile.first_name %>
<H4>Last Name : <%=@profile.last_name %>
<%= link_to "Edit", edit_profile_path(@profile) %>